version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sampledb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: sampledb
    ports:
      - "8080:8080"
    volumes:
      - .:/app  # ホストのディレクトリをコンテナにマウント
volumes:
  db-data:
